Repository sainik-khaddar/CodeHUB, pull requests merged in 2022-10, with the labels that each got.

#2 Several Solutions added
  20-valid-parentheses/20-valid-parentheses.java
  20-valid-parentheses/NOTES.md
  20-valid-parentheses/README.md
  25-reverse-nodes-in-k-group/25-reverse-nodes-in-k-group.cpp
  25-reverse-nodes-in-k-group/NOTES.md
  25-reverse-nodes-in-k-group/README.md
  26-remove-duplicates-from-sorted-array/26-remove-duplicates-from-sorted-array.java
  26-remove-duplicates-from-sorted-array/NOTES.md
  26-remove-duplicates-from-sorted-array/README.md
  27-remove-element/27-remove-element.java
  27-remove-element/27-remove-element.py
  27-remove-element/NOTES.md
  27-remove-element/README.md
  32-longest-valid-parentheses/32-longest-valid-parentheses.cpp
  32-longest-valid-parentheses/NOTES.md
  32-longest-valid-parentheses/README.md
  38-count-and-say/38-count-and-say.cpp
  38-count-and-say/NOTES.md
  38-count-and-say/README.md
Labels: good first issue, hacktoberfest-accepted

#4 Added Indian Flag C++ code
  indianflag.cpp
Labels: hacktoberfest-accepted

#7 Create 9-palindrome-number.cpp
  9-palindrome-number.cpp
Labels: hacktoberfest-accepted

#11 Added Q.10 of Leetcode, coded in Python3. Time: 33ms, Space: 14.2 MB
  10-regular-expression-matching/README.md
  10-regular-expression-matching/regular-expression-matching.py
Labels: good first issue, hacktoberfest-accepted

#8 231-Power-of-Two
  231-Power-of-Two/231-Power-of-Two.cpp
  231-Power-of-Two/NOTES.md
  231-Power-of-Two/README.md
Labels: good first issue, hacktoberfest-accepted

#13 Create 20. Valid Parentheses
  20. Valid Parentheses
Labels: good first issue, hacktoberfest-accepted

#27 Added solutions to leetcode problems 973, 563, 80 and 103 in java
  103-binary-tree-zigzag-level-order-traversal.java
  563-binary-tree-tilt.java
  80-remove-duplicates-from-sorted-array-II.java
  973-k-closest-points-to-origin.java
Labels: documentation, hacktoberfest-accepted

#26 ReadMe Fixed
  README.md
Labels: good first issue, hacktoberfest-accepted

#25 Create 50-Pow(x,n)
  50-Pow(x,n)
Labels: hacktoberfest-accepted

#24 Added solution to 2410. Maximum Matching of Players With Trainers
  2410-Maximum Matching of Players With Trainers/Readme.md
  2410-Maximum Matching of Players With Trainers/program
Labels: hacktoberfest-accepted

#23 Add files via upload
  28-Find the Index of the First Occurrence in a String/README.md
  28-Find the Index of the First Occurrence in a String/solution.cpp
  50-POW(x,n)/README.md
  50-POW(x,n)/solution.cpp
  77- Combinations/README.md
  77- Combinations/solution.cpp
  80-Remove Duplicates from Sorted Array II/README.md
  80-Remove Duplicates from Sorted Array II/solution.cpp
Labels: hacktoberfest-accepted

#22 Create Minimum Time to Make Rope Colorful.cpp
  Minimum Time to Make Rope Colorful.cpp
  Number of Common Factors.cpp
Labels: good first issue, hacktoberfest-accepted

#21 Added solution of problem number 231
  231-power-of-two/README.md
  231-power-of-two/powerOfTwo.cpp
Labels: hacktoberfest-accepted

#15 Create 27. Remove Element
  27. Remove Element
Labels: good first issue, hacktoberfest-accepted

#20 Added For 1946. Largest Number After Mutating Substring
  1964_Largest-Number-After-Mutating-Substring/numberaftermutating
  1964_Largest-Number-After-Mutating-Substring/readme.md
Labels: hacktoberfest-accepted

#19 Added Q-99 Leetcode, Recover Binary Search Tree in Python
  99-recover-binary-search-tree/99-recover-binary-search-tree.py
  99-recover-binary-search-tree/README.md
  README.md
Labels: good first issue, hacktoberfest-accepted

#18 Hacktober fest
  Candy Leetcode (Greedy Algorithm)
  Climbing Stairs
Labels: hacktoberfest-accepted

#16 Create 35. Search Insert Position
  35. Search Insert Position
Labels: hacktoberfest-accepted

#28 Create Partition Equal Subset Sum.cpp
  Partition Equal Subset Sum.cpp
Labels: hacktoberfest-accepted

#32 210-Course Schedule II
  210-Course Schedule II
Labels: hacktoberfest-accepted

#31 Create Task Scheduler
  Task Scheduler
Labels: hacktoberfest-accepted

#30 Create Decode Ways.cpp
  Decode Ways.cpp
  String to int.cpp
Labels: hacktoberfest-accepted

#29 added bitwise xor of all pairs
  BitwiseXORofAllPairs.java
  MinimizeXOR.java
Labels: documentation, good first issue, hacktoberfest-accepted

#33 Create closestnumbertozero.cpp
  closestnumbertozero.cpp
Labels: hacktoberfest-accepted

#34 Create 2124. Check if All A's Appears Before All B's.cpp
  2124. Check if All A's Appears Before All B's.cpp
Labels: documentation, good first issue, hacktoberfest-accepted

#36 Create 2119. A Number After a Double Reversal.cpp
  2119. A Number After a Double Reversal.cpp
Labels: hacktoberfest-accepted

#37 Create 1512. Number of Good Pairs
  1512. Number of Good Pairs
Labels: hacktoberfest-accepted

#38 added Longest Cycle in a Graph
  2360. Longest Cycle in a Graph/Longest_Cycle_in_a_Graph.java
  2360. Longest Cycle in a Graph/NOTES.md
  2360. Longest Cycle in a Graph/README.md
Labels: hacktoberfest-accepted

#42 LC 785 added
  50-POW(x,n)/README.md
  50-POW(x,n)/solution.cpp
  Leetcode-785/README.md
  Leetcode-785/notes.txt
  Leetcode-785/solution.cpp
Labels: good first issue, hacktoberfest-accepted

#40 Create 59-spiral-matrix-ii.py
  59-spiral-matrix-ii/59-spiral-matrix-ii.py
Labels: hacktoberfest-accepted

#48 Added Solution for 2426 || Interview Ques
  2426-Number of Pairs Satisfying Enequality
Labels: hacktoberfest-accepted

#49 Time: 72ms, Space: 14.9 MB, Optimized Solution
  138-copy-list-with-random-pointer/138-copy-list-with-random-pointer.py
  138-copy-list-with-random-pointer/README.md
  231-power-of-two/README.md
  README.md
Labels: enhancement, good first issue, hacktoberfest-accepted

#47 leetcode 2092 hard
  find all People With Secret/code.cpp
  find all People With Secret/readme.md
Labels: hacktoberfest-accepted

#41 Create Maximum Gap.cpp
  Maximum Gap.cpp
Labels: hacktoberfest-accepted

#43 Create 2011. Final Value of Variable After Performing Operations.cpp
  2011. Final Value of Variable After Performing Operations.cpp
Labels: hacktoberfest-accepted

#44 Added longest word in dictionary
  720. Longest Word in Dictionary/Longest Word in Dictionary.java
  720. Longest Word in Dictionary/NOTES.md
  720. Longest Word in Dictionary/README.md
Labels: good first issue, hacktoberfest-accepted

#51 Create LICENSE.md
  LICENSE.md
Labels: enhancement

#50 Added frog jump after t secs
  1377. Frog Position After T Seconds/Frog Position After T Seconds.java
  1377. Frog Position After T Seconds/NOTES.md
  1377. Frog Position After T Seconds/README.md
Labels: hacktoberfest-accepted

#58 Added 455-assign-cookies
  455-assign-cookies/455-assign-cookies.java
  455-assign-cookies/NOTES.md
  455-assign-cookies/README.md
Labels: hacktoberfest-accepted

#59 Add jump game Pr#1 for hacktoberfest
  Jump_GameIl.cpp
Labels: good first issue, hacktoberfest-accepted

#53 Create Readme.md
  59-spiral-matrix-ii/Readme.md
Labels: hacktoberfest-accepted

#54 Create Minimum Initial Energy to Finish Tasks.py
  Minimum Initial Energy to Finish Tasks.py
Labels: hacktoberfest-accepted

#55 Add solution for Leetcode-2425
  2425-Bitwise-XOR-of-All-Pairings/2425-Bitwise-XOR-of-All-Pairings.cpp
  2425-Bitwise-XOR-of-All-Pairings/NOTES.md
Labels: hacktoberfest-accepted

#56 Create Path Sum
  Path Sum
Labels: hacktoberfest-accepted

#57 Create 3 Sum
  3 Sum
Labels: hacktoberfest-accepted

#60 52-N-Queens-II.cpp
  52-N-Queens-II.cpp
Labels: hacktoberfest-accepted

#61 added 39-combination-sum probleam
  39-combination-sum/39-combination-sum.cpp
  39-combination-sum/Notes.md
Labels: hacktoberfest-accepted

#67 Add leetcode hard problem #pr2 for hacktoberfest
  GrumpyBookstoreOwner.cpp
  Scramble_String.cpp
Labels: good first issue, hacktoberfest-accepted

#68 Leetcode Daily Problem of 4th October 2022 in C++(Path Sum)
  Count Good Nodes in Binary Tree.cpp
  Path Sum.cpp
Labels: good first issue, hacktoberfest-accepted

#69 Top_K_Frequent_Elements.cpp
  Top_K_Frequent_Elements.cpp
Labels: good first issue, hacktoberfest-accepted

#71 Added leetcode solutions.
  4-Median of Two Sorted Arrays/Median of Two Sorted Arrays.java
  4-Median of Two Sorted Arrays/README.md
Labels: hacktoberfest-accepted

#72 Sed Passwords.c
  Sed Passwords.c/Sed Passwords.c
Labels: hacktoberfest-accepted

#73 Q-295 Leetcode solution added, Fixed README typos
  295-find-median-from-data-stream/295-find-median-from-datastream.py
  295-find-median-from-data-stream/README.md
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted

#75 Trapping rain water
  42-trapping-rain-water./ReadMe.md
  42-trapping-rain-water./trapping-rainwater.cpp
Labels: hacktoberfest-accepted

#76 pr#3 for the issue i created
  Find_substring_with_given_value.js
Labels: hacktoberfest-accepted

#78 issue solved which codeforce problem opened by u
  CODEFORCE_PROBLEM_E.py
Labels: enhancement, hacktoberfest-accepted

#93 Added two different approaches
  283. Move Zeroes/283. Move Zeroes.java
  283. Move Zeroes/NOTES.md
Labels: hacktoberfest-accepted

#86 Initial Commit
  Leetcode.GCD-Sort-of-an-Array.cpp
  Leetcode.Graph-Connecitivity-With-Threshold.cpp
  Leetcode.Number-of-Good-Paths.cpp
  Leetcode.Similar-String-Groups.cpp
Labels: hacktoberfest-accepted

#79 Add Solution for Removing Stars From a String
  2390. Removing Stars From a String/Removing-Stars-From-a-String.cpp
Labels: good first issue, hacktoberfest-accepted

#81 added one solution for hacktoberfest #PR1
  Map_Sum_Pair.cpp
Labels: good first issue, hacktoberfest-accepted

#85 Thank you
  Generate_parenthesis.cpp
Labels: hacktoberfest-accepted

#83 problem no 3 for contribution #PR3
  closest_room.cpp
Labels: hacktoberfest-accepted

#84 #Pr4 for Hacktoberfest
  max_xor.cpp
Labels: hacktoberfest-accepted

#92 Added (Leetcode-160)
  Intersection of Two Linked Lists (Leetcode-160)
  Maximum Points You Can Obtain from Cards (Leetcode - 1423)
Labels: good first issue, hacktoberfest-accepted

#105 87_ScrambleString.py
  87 Scramble String/Scramble_String.py
Labels: hacktoberfest-accepted

#98 218-The-Skyline-Problem.cpp
  218-The-Skyline-Problem.cpp
Labels: hacktoberfest-accepted

#107 Leetcode 547 added
  Leetcode-547/README.md
  Leetcode-547/notes.txt
  Leetcode-547/solution.cpp
  Leetcode-787/README.md
  Leetcode-787/notes.txt
  Leetcode-787/solution.cpp
Labels: hacktoberfest-accepted

#109 Some Codeforces Solutions
  1285C-Fadi and LCM/1285C.cpp
  1350B-Orac and Models/1350B.cpp
  1375C-Element Extermination/1375C.cpp
  1624D-Palindromes Coloring/1624D.cpp
  1709A-Three Doors/1709A.cpp
  1709B-Also Try Minecraft/1709B.cpp
  1709D-Rorororobot/1709D.cpp
  1711A-Perfect Permutation/1711A.cpp
  1711B-Party/1711B.cpp
  2SUM/2SUM.cpp
Labels: good first issue, hacktoberfest-accepted

#110 Add files via upload
  CSES_Euler problems/1_RoughWork.txt
  CSES_Euler problems/Apartments.bin
  CSES_Euler problems/Apartments.cpp
  CSES_Euler problems/Bit_Strings.bin
  CSES_Euler problems/Bit_Strings.cpp
  CSES_Euler problems/Coin_Combinations_I.bin
  CSES_Euler problems/Coin_Combinations_I.cpp
  CSES_Euler problems/Coin_Combinations_II.bin
  CSES_Euler problems/Coin_Combinations_II.cpp
  CSES_Euler problems/Collecting_Numbers.bin
  CSES_Euler problems/Collecting_Numbers.cpp
  CSES_Euler problems/Collecting_Numbers_II.bin
  CSES_Euler problems/Collecting_Numbers_II.cpp
  CSES_Euler problems/Concert_Tickets.bin
  CSES_Euler problems/Concert_Tickets.cpp
  CSES_Euler problems/Dice_Combinations.bin
  CSES_Euler problems/Dice_Combinations.cpp
  CSES_Euler problems/Ferris_Wheel.bin
  CSES_Euler problems/Ferris_Wheel.cpp
  CSES_Euler problems/Grid_Paths.bin
  CSES_Euler problems/Grid_Paths.cpp
  CSES_Euler problems/Josephus_Problem_I.bin
  CSES_Euler problems/Josephus_Problem_I.cpp
  CSES_Euler problems/Josephus_Problem_II.bin
  CSES_Euler problems/Josephus_Problem_II.cpp
  CSES_Euler problems/Minimizing_Coins.bin
  CSES_Euler problems/Minimizing_Coins.cpp
  CSES_Euler problems/Missing_number.bin
  CSES_Euler problems/Missing_number.cpp
  CSES_Euler problems/Movie_Festival.bin
  CSES_Euler problems/Movie_Festival.cpp
  CSES_Euler problems/Nested_Ranges_Check.bin
  CSES_Euler problems/Nested_Ranges_Check.cpp
  CSES_Euler problems/Playlist.bin
  CSES_Euler problems/Playlist.cpp
  CSES_Euler problems/Playlist.exe
  CSES_Euler problems/Removing_Digits.cpp
  CSES_Euler problems/Stick_Lengths.bin
  CSES_Euler problems/Stick_Lengths.cpp
  CSES_Euler problems/Subarray_Sums_I.bin
  CSES_Euler problems/Subarray_Sums_I.cpp
  CSES_Euler problems/Towers.bin
  CSES_Euler problems/Towers.cpp
  CSES_Euler problems/Traffic_Lights.bin
  CSES_Euler problems/Traffic_Lights.cpp
  CSES_Euler problems/Trailing_Zeros.bin
  CSES_Euler problems/Trailing_Zeros.cpp
  CSES_Euler problems/Two_Sets.bin
  CSES_Euler problems/Two_Sets.cpp
  CSES_Euler problems/coin_piles.cpp
  CSES_Euler problems/template.cpp
  CSES_Euler problems/two_knights.bin
  CSES_Euler problems/two_knights.cpp
  CSES_Euler problems/weird_algo.bin
  CSES_Euler problems/weird_algo.cpp
  CSES_Euler problems/weird_algo.exe
Labels: good first issue, hacktoberfest-accepted

#111 58. Length of Last Word
  58-length-of-last-word/58-length-of-last-word.cpp
  58-length-of-last-word/NOTES.md
  58-length-of-last-word/README.md
Labels: hacktoberfest-accepted

#112 1092. Shortest Common Supersequence
  1092-shortest-common-supersequence/1092-shortest-common-supersequence.cpp
  1092-shortest-common-supersequence/NOTES.md
  1092-shortest-common-supersequence/README.md
Labels: hacktoberfest-accepted

#101 Create 2416- Sum of prefix score of String
  2416- Sum of prefix score of String
Labels: good first issue, hacktoberfest-accepted

#115 LC 1584 added
  Leetcode-1584/README.md
  Leetcode-1584/notes.txt
  Leetcode-1584/solution.cpp
Labels: hacktoberfest-accepted

#118 this commit fixes #108
  542- 01 Matrix.cpp
Labels: hacktoberfest-accepted

#113 Create Add One Row to Tree
  Add One Row to Tree
Labels: hacktoberfest-accepted

#116 Added Leetcode-1423
  (Leetcode - 1423) Maximum Points You Can Obtain from Cards
Labels: hacktoberfest-accepted

#117 29. Divide Two Integers
  29-divide-two-integers/29-divide-two-integers.cpp
  29-divide-two-integers/NOTES.md
  29-divide-two-integers/README.md
Labels: enhancement, hacktoberfest-accepted

#114 Create Time Based Key-Value Store
  Time Based Key-Value Store
Labels: duplicate

#135 HACKTOBERFEST-2022
  975-ODD EVEN JUMP SOLUTION.cpp.txt
  READ.md.txt
Labels: hacktoberfest-accepted

#130 Lucy and Palindromes.java
  Lucy and Palindromes.java/Lucy and Palindromes.java
Labels: hacktoberfest-accepted

#131 Hacktoberfest code2
  2414- Length of the Longest Alphabetical Continuous Substring.cpp
  860 - Lemonade change.cpp
Labels: hacktoberfest-accepted

#125 added 90-subsetsII problem
  90-Subsets-II/90-subsets-II.cpp
  90-Subsets-II/notes.md
Labels: hacktoberfest-accepted

#124 971. Flip Binary Tree To Match Preorder Traversal
  971-flip-binary-tree-to-match-preorder-traversal/971-flip-binary-tree-to-match-preorder-traversal.cpp
  971-flip-binary-tree-to-match-preorder-traversal/NOTES.md
  971-flip-binary-tree-to-match-preorder-traversal/README.md
Labels: hacktoberfest-accepted

#146 Function for LCA of Binary Search Tree Code is added
  LCA_BST.cpp
Labels: hacktoberfest-accepted

#160 Added LCS
  Longest_Common_Subsequence.py
Labels: good first issue, hacktoberfest-accepted
